[theme]
primaryColor = "#1f77b4"             # Blue for buttons and accents
backgroundColor = "#ffffff"          # White background for the main page
secondaryBackgroundColor = "#f0f0f0" # Light grey for the sidebar background
textColor = "#1f1f1f"                # Dark grey text color
font = "sans serif"                  # Font type
